#lang planet tracer/tracer

(define (fooooooooooooooo a b)
  (build-list a b))

(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))
(fooooooooooooooo 5 (lambda(x) 7))